### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JagritThukral** [abhi887/heroku2discord-logdrain#1]
Error L10 (output buffer overflow): drain 'd.dd211a02-782b-4242-96b4-704c1390fc55' dropped 88 messages since 2021-07-

**Comment by abhi887** [comment]
Aware of this, It's cause this logdrain was designed with very low traffic apps in mind and because of that, it was using the flask's built-in development server which can only handle one request at time; Meaning it would break if it was used with any app that would be getting concurrent requests.

**Comment by abhi887** [comment]
`Flask` 's built-in development server is now replaced with `gunicorn`, meaning massively increased scalability.
Re-deploy your app to incorporate new update using the `deploy to heroku` button.

**Comment by JagritThukral** [comment]
@abhi887 i still face the problem . My bot logs huge text error so I need a track of it . So is there are any solution for high traffic apps. Maybe put logs that is sent at same time into a embed (keeping character limit in mind)

**Comment by abhi887** [comment]
Hey @legendary0001, thanks for the suggestion of embed and combining some logs into a single one, I've added a way to "batch" multiple logs into a single discord message (just the relay part and not actual clubbing of logs) and converted the standard `\logs` view into a async view adding to efficiency of the server.

You can now redeploy the app with latest changes and I've also added a new config field for heroku deployments so that you just need to specify "true" for the `LONG_LOGS_ENABLED` env var, hope this helps.
